version: "3.9"

services:
  postgresql:
    image: postgres:latest
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cmsapp
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
      - "5455:5432"
    hostname: postgres
    restart: always
    user: root